CREATE TABLE IF NOT EXISTS `Products` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    `description` VARCHAR(200) DEFAULT 'No description',
    `category` VARCHAR(25) NOT NULL DEFAULT 'Other',
    `stock` SMALLINT(5) UNSIGNED NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `unit_price` FLOAT(6, 2) UNSIGNED NOT NULL,
    `visibility` TINYINT(1) DEFAULT 1 NOT NULL,
    PRIMARY KEY (`id`)
)